name: sweep

on:
  schedule:
    - cron: "17 * * * *"

concurrency:
  group: open-grind-build

jobs:
  sweep:
    runs-on: ["open-grind-orchestrator"]
    timeout-minutes: 20
    steps:
      - name: Delete leaked builders
        env:
          OPEN_GRIND_FORGEJO_TOKEN: ${{ secrets.OPEN_GRIND_FORGEJO_TOKEN }}
          # box a
          OPEN_GRIND_CHERRY_API_TOKEN: ${{ secrets.OPEN_GRIND_CHERRY_API_TOKEN }}
          OPEN_GRIND_CHERRY_PROJECT_ID: ${{ secrets.OPEN_GRIND_CHERRY_PROJECT_ID }}
          # box b
          OPEN_GRIND_VULTR_API_KEY: ${{ secrets.OPEN_GRIND_VULTR_API_KEY }}
          # box c
          OPEN_GRIND_HETZNER_API_TOKEN: ${{ secrets.OPEN_GRIND_HETZNER_API_TOKEN }}
          # box d
          OPEN_GRIND_SCALEWAY_SECRET_KEY: ${{ secrets.OPEN_GRIND_SCALEWAY_SECRET_KEY }}
          OPEN_GRIND_SCALEWAY_PROJECT_ID: ${{ secrets.OPEN_GRIND_SCALEWAY_PROJECT_ID }}
          # box e
          OPEN_GRIND_DIGITALOCEAN_TOKEN: ${{ secrets.OPEN_GRIND_DIGITALOCEAN_TOKEN }}
        run: |
          fetch-repo
          bash repo/ci/sweep.sh
