runner:
  capacity: 1
  labels:
    - open-grind-orchestrator:docker://git.opengrind.org/open-grind/open-grind-orchestrator@sha256:c344bfffa64324230c6c25d389b3a2ecfd235cd9eefa2495275fb534b9f3245c
container:
  privileged: false
  valid_volumes: []
  docker_host: "-"
  network: ""
server:
  connections:
    open-grind-orchestrator:
      url: https://git.opengrind.org/
      uuid: 00000000-0000-0000-0000-000000000000
      token: 0000000000000000000000000000000000000000
