runner:
  capacity: 1
  labels:
    - open-grind-orchestrator:docker://git.opengrind.org/open-grind/open-grind-orchestrator@sha256:63365108116661c448032d4f005f0ac82012fc11aef2906f8df16cebf5abe0cf
container:
  privileged: false
  valid_volumes: []
  docker_host: "-"
  network: ""
server:
  connections:
    open-grind-orchestrator:
      url: https://git.opengrind.org/
      uuid: 00000000-0000-0000-0000-000000000000
      token: 0000000000000000000000000000000000000000
