runner:
  capacity: 1
  labels:
    - open-grind-orchestrator:docker://git.opengrind.org/open-grind/open-grind-orchestrator@sha256:eca907dce8397dffed740d50b8365aeab3a9d907e10b4a22e1623ae89898b001
container:
  privileged: false
  valid_volumes: []
  docker_host: "-"
  network: ""
server:
  connections:
    open-grind-orchestrator:
      url: https://git.opengrind.org/
      uuid: 00000000-0000-0000-0000-000000000000
      token: 0000000000000000000000000000000000000000
